How many late days are you using for this assignment? 0

In [20]:
# Imports and pip installations (if needed)
import pandas as pd

# Part 1: Load the dataset

In [21]:
# Load the given datasets
stcat = pd.read_csv("chronic_kidney_disease_categorical.csv")
stnum = pd.read_csv("chronic_kidney_disease_numerical.csv")
print("Dataset Categorical","\n",stcat,"\n")
print("Dataset Numerical",stnum)

# Print the data

Dataset Categorical
      unique_id   al   su       rbc        pc         pcc          ba  htn  \
0       224481  3.0  NaN       NaN       NaN  notpresent  notpresent  yes
1       992643  0.0  0.0       NaN       NaN  notpresent  notpresent   no
2       308740  1.0  0.0  abnormal  abnormal  notpresent  notpresent  yes
3       450314  1.0  0.0       NaN    normal  notpresent  notpresent   no
4       881763  0.0  0.0    normal    normal  notpresent  notpresent   no
..         ...  ...  ...       ...       ...         ...         ...  ...
425     769512  0.0  0.0    normal    normal  notpresent  notpresent   no
426     872034  2.0  1.0  abnormal  abnormal  notpresent     present  yes
427     643007  NaN  NaN       NaN    normal  notpresent  notpresent  yes
428     840392  NaN  NaN       NaN       NaN  notpresent  notpresent  yes
429     856244  0.0  0.0       NaN    normal  notpresent  notpresent  yes

      dm  cad appet   pe  ane  Target
0    yes   no  good  yes   no     ckd
1     no   no  good   no   no  notckd
2     no   no  good  yes   no     ckd
3     no   no  good   no  yes     ckd
4     no   no  good   no   no  notckd
..   ...  ...   ...  ...  ...     ...
425   no   no  good   no   no  notckd
426  yes  yes  poor   no   no     ckd
427  yes  yes  poor   no   no     ckd
428   no   no  poor   no   no     ckd
429  yes   no  poor   no   no     ckd

[430 rows x 14 columns]

Dataset Numerical      unique_id   age     bp    bgr     bu   sc    sod  pot  hemo   pcv  \
0       203694  38.0   80.0   99.0   19.0  0.5  147.0  3.5  13.6  44.0
1       938027  43.0   60.0  108.0   25.0  1.0  144.0  5.0  17.8  43.0
2       421471  37.0   60.0  111.0   35.0  0.8  135.0  4.1  16.2  50.0
3       764115  70.0   90.0  144.0  125.0  4.0  136.0  4.6  12.0  37.0
4       240975  47.0   80.0   95.0   35.0  0.9  140.0  4.1   NaN   NaN
..         ...   ...    ...    ...    ...  ...    ...  ...   ...   ...
415     522912  56.0   80.0  165.0   55.0  1.8    NaN  NaN  13.5  40.0
416     475200  64.0  100.0  163.0   54.0  7.2  140.0  4.6   7.9  26.0
417     168242  48.0   60.0  112.0   44.0  1.2  142.0  4.9  14.5  44.0
418     474407  21.0   90.0  107.0   40.0  1.7  125.0  3.5   8.3  23.0
419     926033  50.0   70.0  230.0   50.0  2.2    NaN  NaN  12.0  41.0

        wbcc  rbcc
0     7300.0   6.4
1     7200.0   5.5
2     5500.0   5.7
3     8200.0   4.5
4        NaN   NaN
..       ...   ...
415  11800.0   5.0
416   7500.0   3.4
417   9400.0   6.4
418  12400.0   3.9
419  10400.0   4.6

[420 rows x 12 columns]

# Part 2: Analyze the Dataset

Refer to this: https://archive.ics.uci.edu/dataset/336/chronic+kidney+disease

Explain what the each data is in your own words. What are the features and labels? Are the features in the given datasets : categorical, numerical or both? Give 3 examples of categorical and numerical columns each (if they exist)

Answer:

The given data contains medical data of a patient and treis to predict if the patient has Chronic Kidney Disease.
Each column represents the attribute or test result while the rows contain the medical information corresponding to an attribute.

Features are the variables given from the tests in this case used to predict other variables. Labels are the target variables we try to predict.

Categorical features examples- Gender, apetite, sugar

Numerical features examples-age,blood pressure,blood glucose random

# Part 3: Data Preprocessing

A fundamental skill in Machine Learning is mastering the art of data cleaning and preprocessing. In this assignment, you will learn and apply essential data cleaning techniques to transform a raw dataset into a clean, ready-to-use form which you can use for regression or classification tasks. By the end of this assignment, you'll have a fully clean dataset and a solid foundation in preparing data for various machine learning models.

## Part 3.1 : Drop Duplicate rows

Let's start by checking if the given datasets have any duplicate rows (same Unique Id). Use pandas to identify and remove these duplicate rows from the given dataset

In [22]:
# For the numerical dataset, check if there are duplicate rows in the dataset. If yes, print total number of duplicate rows


# Drop these duplicate rows


# Repeat the same for categorical dataset. Print the duplicate rows and drop them

duplicate_num = stnum[stnum.duplicated()]
num_duplicates_count = duplicate_num.shape[0]

# Print the number of duplicate rows
print(f"Numerical Dataset: Total number of duplicate rows = {num_duplicates_count}")

# If duplicates exist, print them
if num_duplicates_count > 0:
    print("Duplicate rows in numerical dataset:")
    print(duplicate_num)

# Drop duplicate rows in the numerical dataset
stnum= stnum.drop_duplicates()

# Check for duplicates in the categorical dataset
duplicate_cat = stcat[stcat.duplicated()]
cat_duplicates_count = duplicate_cat.shape[0]

# Print the number of duplicate rows
print(f"\nCategorical Dataset: Total number of duplicate rows = {cat_duplicates_count}")

# If duplicates exist, print them
if cat_duplicates_count > 0:
    print("Duplicate rows in categorical dataset:")
    print(duplicate_cat)

# Drop duplicate rows in the categorical dataset
stcat= stcat.drop_duplicates()

# Optionally, print the shape of datasets after dropping duplicates
print(f"\nNumerical Dataset shape after deduplication: {stnum.shape}")
print(f"Categorical Dataset shape after deduplication: {stcat.shape}")

Numerical Dataset: Total number of duplicate rows = 30
Duplicate rows in numerical dataset:
     unique_id   age     bp    bgr     bu   sc    sod  pot  hemo   pcv  \
107     872034  70.0   90.0  184.0   98.6  3.3  138.0  3.9   5.8   NaN
149     721270  58.0   70.0  102.0   48.0  1.2  139.0  4.3  15.0  40.0
171     240975  47.0   80.0   95.0   35.0  0.9  140.0  4.1   NaN   NaN
173     441170  79.0   80.0  111.0   44.0  1.2  146.0  3.6  16.3  40.0
185     261137  35.0   60.0  105.0   39.0  0.5  135.0  3.9  14.7  43.0
194     769512  38.0   60.0   91.0   36.0  0.7  135.0  3.7  14.0  46.0
213     354223  64.0   70.0   97.0   27.0  0.7  145.0  4.8  13.8  49.0
244     302906  59.0  100.0    NaN   96.0  6.4    NaN  NaN   6.6   NaN
245     431871  57.0   60.0  132.0   18.0  1.1  150.0  4.7  15.4  42.0
248     687021  52.0   80.0   99.0   25.0  0.8  135.0  3.7  15.0  52.0
249     843449  30.0   80.0  131.0   38.0  1.0  147.0  3.8  14.1  45.0
265     628271  65.0   90.0  270.0   39.0  2.0    NaN  NaN  12.0  36.0
273     862719  61.0   80.0  131.0   23.0  0.8  140.0  4.1  11.3  35.0
292     202793  74.0   60.0  108.0   68.0  1.8    NaN  NaN   NaN   NaN
299     224481  54.0   60.0  125.0   21.0  1.3  137.0  3.4  15.0  46.0
300     856244  75.0   80.0  156.0   45.0  2.4  140.0  3.4  11.6  35.0
315     572140  55.0   80.0  104.0   28.0  0.9  142.0  4.8  17.3  52.0
324     501321   4.0    NaN   99.0   23.0  0.6  138.0  4.4  12.0  34.0
327     283427  55.0   80.0  140.0   49.0  0.5  150.0  4.9  15.7  47.0
331     856244  75.0   80.0  156.0   45.0  2.4  140.0  3.4  11.6  35.0
342     938027  43.0   60.0  108.0   25.0  1.0  144.0  5.0  17.8  43.0
345     337834  48.0   70.0  117.0   56.0  3.8  111.0  2.5  11.2  32.0
360     643007  76.0   90.0   93.0  155.0  7.3  132.0  4.9   NaN   NaN
362     840392  47.0   80.0  114.0   87.0  5.2  139.0  3.7  12.1   NaN
376     415906  60.0   80.0  131.0   10.0  0.5  146.0  5.0  14.5  41.0
380     708255   3.0    NaN    NaN   22.0  0.7    NaN  NaN  10.7  34.0
385     118191  42.0   70.0   93.0   32.0  0.9  143.0  4.7  16.6  43.0
402     153227  60.0   90.0  490.0   95.0  2.7  131.0  3.8  11.5  35.0
412     583971  62.0   90.0   94.0   25.0  1.1  131.0  3.7   NaN   NaN
413     158929  73.0    NaN   95.0   51.0  1.6  142.0  3.5   NaN   NaN

        wbcc  rbcc
107      NaN   NaN
149   8100.0   4.9
171      NaN   NaN
173   8000.0   6.4
185   5800.0   6.2
194   9100.0   5.8
213   6400.0   4.8
244      NaN   NaN
245  11000.0   4.5
248   6300.0   5.3
249   9400.0   5.3
265   9800.0   4.9
273      NaN   NaN
292      NaN   NaN
299      NaN   NaN
300  10300.0   4.0
315   8200.0   4.8
324      NaN   NaN
327   6700.0   4.9
331  10300.0   4.0
342   7200.0   5.5
345   6700.0   3.9
360      NaN   NaN
362      NaN   NaN
376  10700.0   5.1
380  12300.0   NaN
385   7100.0   5.3
402  12000.0   4.5
412      NaN   NaN
413      NaN   NaN

Categorical Dataset: Total number of duplicate rows = 30
Duplicate rows in categorical dataset:
     unique_id   al   su       rbc        pc         pcc          ba  htn  \
231     856244  0.0  0.0       NaN    normal  notpresent  notpresent  yes
401     628271  2.0  1.0  abnormal    normal  notpresent  notpresent  yes
402     158929  1.0  0.0       NaN       NaN  notpresent  notpresent   no
403     240975  0.0  0.0    normal    normal  notpresent  notpresent   no
404     441170  0.0  0.0    normal    normal  notpresent  notpresent   no
405     337834  4.0  0.0    normal  abnormal     present  notpresent  yes
406     118191  0.0  0.0    normal    normal  notpresent  notpresent   no
407     224481  3.0  NaN       NaN       NaN  notpresent  notpresent  yes
408     302906  NaN  NaN       NaN       NaN  notpresent  notpresent  yes
409     938027  0.0  0.0    normal    normal  notpresent  notpresent   no
410     572140  0.0  0.0    normal    normal  notpresent  notpresent   no
411     283427  0.0  0.0    normal    normal  notpresent  notpresent   no
412     202793  NaN  NaN       NaN       NaN  notpresent  notpresent  yes
413     501321  1.0  0.0       NaN    normal  notpresent  notpresent   no
414     153227  3.0  5.0  abnormal    normal  notpresent     present  yes
415     843449  0.0  0.0    normal    normal  notpresent  notpresent   no
416     415906  0.0  0.0    normal    normal  notpresent  notpresent   no
417     708255  2.0  0.0    normal    normal  notpresent  notpresent   no
418     862719  0.0  0.0       NaN    normal  notpresent  notpresent   no
419     354223  0.0  0.0    normal    normal  notpresent  notpresent   no
420     721270  0.0  0.0    normal    normal  notpresent  notpresent   no
421     687021  0.0  0.0    normal    normal  notpresent  notpresent   no
422     583971  1.0  0.0       NaN    normal  notpresent  notpresent  yes
423     261137  0.0  0.0    normal    normal  notpresent  notpresent   no
424     431871  0.0  0.0    normal    normal  notpresent  notpresent   no
425     769512  0.0  0.0    normal    normal  notpresent  notpresent   no
426     872034  2.0  1.0  abnormal  abnormal  notpresent     present  yes
427     643007  NaN  NaN       NaN    normal  notpresent  notpresent  yes
428     840392  NaN  NaN       NaN       NaN  notpresent  notpresent  yes
429     856244  0.0  0.0       NaN    normal  notpresent  notpresent  yes

      dm  cad appet   pe  ane  Target
231  yes   no  poor   no   no     ckd
401  yes   no  poor   no  yes     ckd
402   no   no  good   no   no     ckd
403   no   no  good   no   no  notckd
404   no   no  good   no   no  notckd
405   no   no  poor  yes  yes     ckd
406   no   no  good   no   no  notckd
407  yes   no  good  yes   no     ckd
408  yes   no  good   no  yes     ckd
409   no   no  good   no   no  notckd
410   no   no  good   no   no  notckd
411   no   no  good   no   no  notckd
412  yes   no  good   no   no     ckd
413   no   no  good   no   no     ckd
414  yes   no  good   no   no     ckd
415   no   no  good   no   no  notckd
416   no   no  good   no   no  notckd
417   no   no  good   no   no     ckd
418   no   no  good   no   no     ckd
419   no   no  good   no   no  notckd
420   no   no  good   no   no  notckd
421   no   no  good   no   no  notckd
422   no   no  good  yes  yes     ckd
423   no   no  good   no   no  notckd
424   no   no  good   no   no  notckd
425   no   no  good   no   no  notckd
426  yes  yes  poor   no   no     ckd
427  yes  yes  poor   no   no     ckd
428   no   no  poor   no   no     ckd
429  yes   no  poor   no   no     ckd

Numerical Dataset shape after deduplication: (390, 12)
Categorical Dataset shape after deduplication: (400, 14)

## Part 3.2: Combine two differents datasets

A good skill to have is to know how to combine 2 different datasets.

Are all the unique ids are present in both datasets? Why do you think so? If not, what do the rows that are missing from one of the datasets look like in the combined table?

Answer-There are unique_id's present in categorical data set not present in numerical data set. In the combined table, they have no values in them, replaced with NAN

In [23]:


combined = pd.merge(stnum, stcat, on="unique_id", how='outer')


print("\nCombined Dataset:")
print(combined)

Combined Dataset:
     unique_id   age    bp    bgr     bu    sc    sod  pot  hemo   pcv  ...  \
0       102677  59.0  70.0   76.0  186.0  15.0  135.0  7.6   7.1  22.0  ...
1       103570  24.0  80.0  125.0    NaN   NaN  136.0  3.5  15.4  43.0  ...
2       104675  65.0  80.0  215.0  133.0   2.5    NaN  NaN  13.2  41.0  ...
3       105923  90.0  90.0  139.0   89.0   3.0  140.0  4.1  12.0  37.0  ...
4       107297  60.0  70.0    NaN    NaN   NaN    NaN  NaN  16.4  43.0  ...
..         ...   ...   ...    ...    ...   ...    ...  ...   ...   ...  ...
395     995177  69.0  70.0  214.0   96.0   6.3  120.0  3.9   9.4  28.0  ...
396     996076  57.0  60.0  105.0   49.0   1.2  150.0  4.7  15.7  44.0  ...
397     996412  70.0  60.0  120.0   40.0   0.5  140.0  4.6  16.0  43.0  ...
398     997629  35.0   NaN   99.0   30.0   0.5  135.0  4.9  15.4  48.0  ...
399     997876  64.0  70.0  107.0   15.0   NaN    NaN  NaN  12.8  38.0  ...

           pc         pcc          ba  htn   dm  cad appet   pe  ane  Target
0    abnormal  notpresent  notpresent  yes   no   no  poor  yes  yes     ckd
1      normal  notpresent  notpresent   no   no   no  good   no   no  notckd
2      normal     present  notpresent   no  yes   no  good   no   no     ckd
3      normal  notpresent  notpresent  yes  yes   no  good   no   no     ckd
4      normal  notpresent  notpresent   no   no   no  good   no   no  notckd
..        ...         ...         ...  ...  ...  ...   ...  ...  ...     ...
395  abnormal     present     present  yes  yes  yes  good  yes  yes     ckd
396    normal  notpresent  notpresent   no   no   no  good   no   no  notckd
397       NaN  notpresent  notpresent   no   no   no  good   no   no  notckd
398    normal         NaN         NaN   no   no   no  good   no   no  notckd
399    normal  notpresent  notpresent   no   no   no  good   no   no     ckd

[400 rows x 25 columns]

## Part 3.3: Rows with Missing values

Removing missing values from a dataset is important for classification because it ensures the model is trained on complete and accurate data, leading to better performance and reliable predictions. Incomplete data can introduce bias and errors, negatively impacting the model's effectiveness.

In [24]:
# Calculate the percentage of rows that contain atleast one missing value

# Print %

# Drop these rows from the dataset

# Print the Dataset
missing_rows_percentage = (combined.isnull().any(axis=1).sum() / combined.shape[0]) * 100
# Print the percentage
print(f"Percentage of rows that contain at least one missing value: {missing_rows_percentage:.2f}%")
# Drop the rows with any missing values
combined_data_cleaned = combined.dropna()
# Print the final dataset after dropping missing values
print("\nDataset after dropping rows with missing values:")
combined_data_cleaned

Percentage of rows that contain at least one missing value: 61.75%

Dataset after dropping rows with missing values:

,unique_id,age,bp,bgr,bu,sc,sod,pot,hemo,pcv,...,pc,pcc,ba,htn,dm,cad,appet,pe,ane,Target
0,102677,59.0,70.0,76.0,186.0,15.0,135.0,7.6,7.1,22.0,...,abnormal,notpresent,notpresent,yes,no,no,poor,yes,yes,ckd
6,109053,64.0,60.0,106.0,27.0,0.7,150.0,3.3,14.4,42.0,...,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
7,114717,41.0,80.0,122.0,25.0,0.8,138.0,5.0,17.1,41.0,...,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
8,118191,42.0,70.0,93.0,32.0,0.9,143.0,4.7,16.6,43.0,...,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
9,118596,74.0,60.0,88.0,50.0,0.6,147.0,3.7,17.2,53.0,...,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,980291,62.0,70.0,122.0,42.0,1.7,136.0,4.7,12.6,39.0,...,abnormal,notpresent,notpresent,yes,yes,no,good,no,no,ckd
391,991031,30.0,80.0,89.0,42.0,0.5,139.0,5.0,16.7,52.0,...,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
394,994377,71.0,70.0,81.0,18.0,0.8,145.0,5.0,14.7,44.0,...,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
395,995177,69.0,70.0,214.0,96.0,6.3,120.0,3.9,9.4,28.0,...,abnormal,present,present,yes,yes,yes,good,yes,yes,ckd
396,996076,57.0,60.0,105.0,49.0,1.2,150.0,4.7,15.7,44.0,...,normal,notpresent,notpresent,no,no,no,good,no,no,notckd

## Part 3.4: Sort the dataset according to the Labels

In [25]:
sorted_data = combined_data_cleaned.sort_values(by='Target').reset_index(drop=True)
# Print the sorted dataset
print("Sorted Dataset:")
sorted_data

Sorted Dataset:

,unique_id,age,bp,bgr,bu,sc,sod,pot,hemo,pcv,...,pc,pcc,ba,htn,dm,cad,appet,pe,ane,Target
0,102677,59.0,70.0,76.0,186.0,15.0,135.0,7.6,7.1,22.0,...,abnormal,notpresent,notpresent,yes,no,no,poor,yes,yes,ckd
1,337834,48.0,70.0,117.0,56.0,3.8,111.0,2.5,11.2,32.0,...,abnormal,present,notpresent,yes,no,no,poor,yes,yes,ckd
2,343710,61.0,80.0,173.0,148.0,3.9,135.0,5.2,7.7,24.0,...,abnormal,notpresent,notpresent,yes,yes,yes,poor,yes,yes,ckd
3,349892,59.0,70.0,424.0,55.0,1.7,138.0,4.5,12.6,37.0,...,abnormal,notpresent,notpresent,yes,yes,yes,good,no,no,ckd
4,353025,40.0,70.0,253.0,150.0,11.9,132.0,5.6,10.9,31.0,...,normal,notpresent,notpresent,yes,yes,no,poor,yes,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,486397,20.0,70.0,123.0,44.0,1.0,135.0,3.8,14.6,44.0,...,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
149,203466,22.0,60.0,97.0,18.0,1.2,138.0,4.3,13.5,42.0,...,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
150,482105,44.0,60.0,95.0,46.0,0.5,138.0,4.2,15.0,50.0,...,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
151,228849,58.0,80.0,100.0,50.0,1.2,140.0,3.5,14.0,50.0,...,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
152,996076,57.0,60.0,105.0,49.0,1.2,150.0,4.7,15.7,44.0,...,normal,notpresent,notpresent,no,no,no,good,no,no,notckd

## Part 3.5: Encoding Categorical data

In this step, we identify and process the categorical columns in the sorted dataset. We map each unique value in these columns to separate "dummy" columns.

For example, the column 'rbc' will be transformed into two columns 'rbc_normal' and 'rbc_abnormal'. If a row's value in 'rbc' is 'normal', the 'rbc_normal' column will be set to 1 and 'rbc_abnormal' will be set to 0.


**Note: Find a correct pandas function to do this **

In [26]:
# Write code here
categorical_columns = ['rbc', 'pc', 'pcc', 'ba', 'htn', 'dm', 'cad', 'appet', 'pe', 'ane', 'Target']

# Print the dataset


# Creating dummy variables for specified categorical columns
encoded_data = pd.get_dummies(sorted_data, columns=categorical_columns)
# Print the encoded dataset
print("Encoded Dataset:")
encoded_data

Encoded Dataset:

,unique_id,age,bp,bgr,bu,sc,sod,pot,hemo,pcv,...,cad_no,cad_yes,appet_good,appet_poor,pe_no,pe_yes,ane_no,ane_yes,Target_ckd,Target_notckd
0,102677,59.0,70.0,76.0,186.0,15.0,135.0,7.6,7.1,22.0,...,True,False,False,True,False,True,False,True,True,False
1,337834,48.0,70.0,117.0,56.0,3.8,111.0,2.5,11.2,32.0,...,True,False,False,True,False,True,False,True,True,False
2,343710,61.0,80.0,173.0,148.0,3.9,135.0,5.2,7.7,24.0,...,False,True,False,True,False,True,False,True,True,False
3,349892,59.0,70.0,424.0,55.0,1.7,138.0,4.5,12.6,37.0,...,False,True,True,False,True,False,True,False,True,False
4,353025,40.0,70.0,253.0,150.0,11.9,132.0,5.6,10.9,31.0,...,True,False,False,True,False,True,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,486397,20.0,70.0,123.0,44.0,1.0,135.0,3.8,14.6,44.0,...,True,False,True,False,True,False,True,False,False,True
149,203466,22.0,60.0,97.0,18.0,1.2,138.0,4.3,13.5,42.0,...,True,False,True,False,True,False,True,False,False,True
150,482105,44.0,60.0,95.0,46.0,0.5,138.0,4.2,15.0,50.0,...,True,False,True,False,True,False,True,False,False,True
151,228849,58.0,80.0,100.0,50.0,1.2,140.0,3.5,14.0,50.0,...,True,False,True,False,True,False,True,False,False,True
152,996076,57.0,60.0,105.0,49.0,1.2,150.0,4.7,15.7,44.0,...,True,False,True,False,True,False,True,False,False,True

In the example we went through above, another solution is to have a single column for the binary variable. In the downstream modeling would this be equivalent? What effect would this have if the categorical variable could take more than 2 values? For example, let's say we have a categorical feature that is "type of condiment" that can take 5 separate values and we are trying to predict the rating of a particular sandwich.

Answer:  This would end up in a loss of ifnormation soemtimes when for example mutiple condiments are being used.

## Part 3.6 : Remove Outliers from Numerical Columns

Outliers can disproportionately influence the fit of a regression model, potentially leading to a model that does not generalize well therefore it is important that we remove outliers from the numerical columns of the dataset.

For this dataset, we define an outlier to be 3 times the standard deviation from the mean. Drop these outliers from the dataset

In [27]:
# Remove outliers
numerical_columns = ['age', 'bp', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hemo', 'pcv', 'wbcc', 'rbcc']

# Print the dataset

# Display the first few rows of the numerical dataset
for column in numerical_columns:
    mean = encoded_data[column].mean()
    std_dev = encoded_data[column].std()
    # Define the upper and lower bounds for outliers
    lower_bound = mean - 3 * std_dev
    upper_bound = mean + 3 * std_dev
    # Filter the dataset to remove outliers
    encoded_data = encoded_data[(encoded_data[column] >= lower_bound) & (encoded_data[column] <= upper_bound)]
# Print the dataset after removing outliers
print("Dataset after removing outliers:")
encoded_data

Dataset after removing outliers:

,unique_id,age,bp,bgr,bu,sc,sod,pot,hemo,pcv,...,cad_no,cad_yes,appet_good,appet_poor,pe_no,pe_yes,ane_no,ane_yes,Target_ckd,Target_notckd
2,343710,61.0,80.0,173.0,148.0,3.9,135.0,5.2,7.7,24.0,...,False,True,False,True,False,True,False,True,True,False
5,397388,63.0,100.0,280.0,35.0,3.2,143.0,3.5,13.0,40.0,...,False,True,True,False,True,False,True,False,True,False
7,438182,73.0,80.0,253.0,142.0,4.6,138.0,5.8,10.5,33.0,...,False,True,True,False,True,False,True,False,True,False
8,474407,21.0,90.0,107.0,40.0,1.7,125.0,3.5,8.3,23.0,...,True,False,True,False,True,False,False,True,True,False
9,475200,64.0,100.0,163.0,54.0,7.2,140.0,4.6,7.9,26.0,...,True,False,True,False,False,True,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,486397,20.0,70.0,123.0,44.0,1.0,135.0,3.8,14.6,44.0,...,True,False,True,False,True,False,True,False,False,True
149,203466,22.0,60.0,97.0,18.0,1.2,138.0,4.3,13.5,42.0,...,True,False,True,False,True,False,True,False,False,True
150,482105,44.0,60.0,95.0,46.0,0.5,138.0,4.2,15.0,50.0,...,True,False,True,False,True,False,True,False,False,True
151,228849,58.0,80.0,100.0,50.0,1.2,140.0,3.5,14.0,50.0,...,True,False,True,False,True,False,True,False,False,True
152,996076,57.0,60.0,105.0,49.0,1.2,150.0,4.7,15.7,44.0,...,True,False,True,False,True,False,True,False,False,True

## Part 3.7 : Normalize the Numerical Columns

Normalizing numerical attributes ensures that all features contribute equally to the model by scaling them to a consistent range, which improves model performance and convergence. It prevents features with larger scales from disproportionately influencing the model's learning process.

In [28]:
# Normalize the all Numerical Attributes in the dataset.

# Print the dataset
for column in numerical_columns:
    encoded_data[column] = (encoded_data[column] - encoded_data[column].min()) / (encoded_data[column].max() - encoded_data[column].min())
# Print the dataset after normalization
print("Dataset after normalizing numerical attributes:")
encoded_data

Dataset after normalizing numerical attributes:

,unique_id,age,bp,bgr,bu,sc,sod,pot,hemo,pcv,...,cad_no,cad_yes,appet_good,appet_poor,pe_no,pe_yes,ane_no,ane_yes,Target_ckd,Target_notckd
2,343710,0.743243,0.50,0.442060,0.901961,0.432099,0.500000,0.793103,0.000000,0.032258,...,False,True,False,True,False,True,False,True,True,False
5,397388,0.770270,1.00,0.901288,0.163399,0.345679,0.766667,0.206897,0.524752,0.548387,...,False,True,True,False,True,False,True,False,True,False
7,438182,0.905405,0.50,0.785408,0.862745,0.518519,0.600000,1.000000,0.277228,0.322581,...,False,True,True,False,True,False,True,False,True,False
8,474407,0.202703,0.75,0.158798,0.196078,0.160494,0.166667,0.206897,0.059406,0.000000,...,True,False,True,False,True,False,False,True,True,False
9,475200,0.783784,1.00,0.399142,0.287582,0.839506,0.666667,0.586207,0.019802,0.096774,...,True,False,True,False,False,True,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,486397,0.189189,0.25,0.227468,0.222222,0.074074,0.500000,0.310345,0.683168,0.677419,...,True,False,True,False,True,False,True,False,False,True
149,203466,0.216216,0.00,0.115880,0.052288,0.098765,0.600000,0.482759,0.574257,0.612903,...,True,False,True,False,True,False,True,False,False,True
150,482105,0.513514,0.00,0.107296,0.235294,0.012346,0.600000,0.448276,0.722772,0.870968,...,True,False,True,False,True,False,True,False,False,True
151,228849,0.702703,0.50,0.128755,0.261438,0.098765,0.666667,0.206897,0.623762,0.870968,...,True,False,True,False,True,False,True,False,False,True
152,996076,0.689189,0.00,0.150215,0.254902,0.098765,1.000000,0.620690,0.792079,0.677419,...,True,False,True,False,True,False,True,False,False,True

## Part 3.8: Remove Unnecessary columns

Are there any columns in this dataset which are not appropriate for modeling and predictions? Which column(s)? Justify their exclusion and remove them

Answer: the unique_id column . They act as noise in data modelling, making it more difficult to pick

In [29]:
#Remove that column

# Print the dataset
cleaned_data = encoded_data.drop(columns="unique_id")
# Print the dataset after removing inappropriate columns
print("Dataset after removing inappropriate columns:")
print(cleaned_data.head(15))

Dataset after removing inappropriate columns:
         age    bp       bgr        bu        sc       sod       pot  \
2   0.743243  0.50  0.442060  0.901961  0.432099  0.500000  0.793103
5   0.770270  1.00  0.901288  0.163399  0.345679  0.766667  0.206897
7   0.905405  0.50  0.785408  0.862745  0.518519  0.600000  1.000000
8   0.202703  0.75  0.158798  0.196078  0.160494  0.166667  0.206897
9   0.783784  1.00  0.399142  0.287582  0.839506  0.666667  0.586207
10  0.729730  0.00  0.935622  0.169935  0.160494  0.333333  0.034483
12  0.675676  0.75  0.253219  0.633987  0.777778  0.366667  0.655172
13  0.851351  0.25  0.618026  0.562092  0.728395  0.000000  0.344828
15  0.540541  0.00  0.399142  0.535948  0.358025  0.700000  0.379310
18  0.756757  0.25  0.223176  0.209150  0.160494  0.533333  0.620690
19  0.662162  0.50  0.618026  0.411765  0.432099  0.566667  0.689655
20  0.783784  0.00  0.725322  0.313725  0.481481  0.566667  0.862069
22  0.878378  0.00  0.206009  0.751634  0.604938  0.533333  0.689655
23  0.878378  0.25  0.639485  0.470588  0.395062  0.433333  0.517241
29  0.716216  0.50  1.000000  0.163399  0.111111  0.066667  0.206897

        hemo       pcv      wbcc  ...  cad_no  cad_yes  appet_good  \
2   0.000000  0.032258  0.395161  ...   False     True       False
5   0.524752  0.548387  0.443548  ...   False     True        True
7   0.277228  0.322581  0.233871  ...   False     True        True
8   0.059406  0.000000  0.653226  ...    True    False        True
9   0.019802  0.096774  0.258065  ...    True    False        True
10  0.019802  0.064516  0.879032  ...    True    False       False
12  0.138614  0.193548  0.169355  ...    True    False        True
13  0.168317  0.161290  0.580645  ...   False     True        True
15  0.207921  0.161290  0.830645  ...    True    False        True
18  0.485149  0.516129  0.290323  ...    True    False        True
19  0.316832  0.354839  0.250000  ...    True    False        True
20  0.178218  0.193548  0.258065  ...    True    False       False
22  0.366337  0.387097  0.879032  ...    True    False       False
23  0.267327  0.322581  0.104839  ...   False     True        True
29  0.267327  0.387097  0.532258  ...    True    False       False

    appet_poor  pe_no  pe_yes  ane_no  ane_yes  Target_ckd  Target_notckd
2         True  False    True   False     True        True          False
5        False   True   False    True    False        True          False
7        False   True   False    True    False        True          False
8        False   True   False   False     True        True          False
9        False  False    True    True    False        True          False
10        True   True   False   False     True        True          False
12       False   True   False    True    False        True          False
13       False  False    True   False     True        True          False
15       False   True   False    True    False        True          False
18       False   True   False    True    False        True          False
19       False  False    True    True    False        True          False
20        True  False    True    True    False        True          False
22        True  False    True    True    False        True          False
23       False   True   False    True    False        True          False
29        True   True   False    True    False        True          False

[15 rows x 35 columns]

## Part 3.9: Export the Cleaned Data

Now that you've completed these cleaning steps you should have a pandas dataframe which is much cleaner and ready for modeling. Our final step is to save our work. Export the DataFrame to a two new formats: csv and json.

In [30]:
# Export the dataframe to a new csv file



cleaned_data.to_csv("cleaned_dataset.csv", index=False)
# Export the cleaned DataFrame to a JSON file
cleaned_data.to_json("cleaned_dataset.json", orient='records', lines=True)

# Part 4: Data conversions with Large Language Models

One powerful use case of ChatGPT (and other generative language models) is cleaning and transforming data. In some cases, these models can directly manipulate loosely structured data that you provide to them into a standard format. In the other cases, you can often prompt the model to create a conversion or extraction script for you in python or Pandas and then run it on your own. 

In this part of the assignment you will prompt 383GPT to explore these capabilities.

## Part 4.1 GPT Data Manipulation

Take the cleaned dataset that you created in part three and output the top 15 rows of that dataset. Then copy the terminal output, open 383gpt and ask it to convert that output to a markdown table. Paste that markdown table in the cell bellow

In [31]:
top_15_rows = cleaned_data.head(15)
# Output the top 15 rows with reset indices
top_15_rows = cleaned_data.head(15).reset_index(drop=True)
# Print the top 15 rows
top_15_rows

,age,bp,bgr,bu,sc,sod,pot,hemo,pcv,wbcc,...,cad_no,cad_yes,appet_good,appet_poor,pe_no,pe_yes,ane_no,ane_yes,Target_ckd,Target_notckd
0,0.743243,0.50,0.442060,0.901961,0.432099,0.500000,0.793103,0.000000,0.032258,0.395161,...,False,True,False,True,False,True,False,True,True,False
1,0.770270,1.00,0.901288,0.163399,0.345679,0.766667,0.206897,0.524752,0.548387,0.443548,...,False,True,True,False,True,False,True,False,True,False
2,0.905405,0.50,0.785408,0.862745,0.518519,0.600000,1.000000,0.277228,0.322581,0.233871,...,False,True,True,False,True,False,True,False,True,False
3,0.202703,0.75,0.158798,0.196078,0.160494,0.166667,0.206897,0.059406,0.000000,0.653226,...,True,False,True,False,True,False,False,True,True,False
4,0.783784,1.00,0.399142,0.287582,0.839506,0.666667,0.586207,0.019802,0.096774,0.258065,...,True,False,True,False,False,True,True,False,True,False
5,0.729730,0.00,0.935622,0.169935,0.160494,0.333333,0.034483,0.019802,0.064516,0.879032,...,True,False,False,True,True,False,False,True,True,False
6,0.675676,0.75,0.253219,0.633987,0.777778,0.366667,0.655172,0.138614,0.193548,0.169355,...,True,False,True,False,True,False,True,False,True,False
7,0.851351,0.25,0.618026,0.562092,0.728395,0.000000,0.344828,0.168317,0.161290,0.580645,...,False,True,True,False,False,True,False,True,True,False
8,0.540541,0.00,0.399142,0.535948,0.358025,0.700000,0.379310,0.207921,0.161290,0.830645,...,True,False,True,False,True,False,True,False,True,False
9,0.756757,0.25,0.223176,0.209150,0.160494,0.533333,0.620690,0.485149,0.516129,0.290323,...,True,False,True,False,True,False,True,False,True,False
10,0.662162,0.50,0.618026,0.411765,0.432099,0.566667,0.689655,0.316832,0.354839,0.250000,...,True,False,True,False,False,True,True,False,True,False
11,0.783784,0.00,0.725322,0.313725,0.481481,0.566667,0.862069,0.178218,0.193548,0.258065,...,True,False,False,True,False,True,True,False,True,False
12,0.878378,0.00,0.206009,0.751634,0.604938,0.533333,0.689655,0.366337,0.387097,0.879032,...,True,False,False,True,False,True,True,False,True,False
13,0.878378,0.25,0.639485,0.470588,0.395062,0.433333,0.517241,0.267327,0.322581,0.104839,...,False,True,True,False,True,False,True,False,True,False
14,0.716216,0.50,1.000000,0.163399,0.111111,0.066667,0.206897,0.267327,0.387097,0.532258,...,True,False,False,True,True,False,True,False,True,False

### Paste the markdown table here

** Caution: ** while language models can perform data conversions they also can * hallucinate * during this process, particularly for bigger datasets. Reflect on this below, how could you mitigate data conversion hallucinations from LLM conversions?

Cross-reference outputs, reduce complexity, manula review, start with simple modelling. Cross referencing with previous datasets is a good way to train and keep track of the model

## Part 4.2 GPT Pandas Prompting

In this section, you will prompt 383GPT to write pandas code manipulations for you.

After working with this data for awhile, we realized we're starting to forget the meanings of the abbreviated column names. Let's ask 383GPT to fix this for us. First, navigate to the [UCI dataset overview](https://archive.ics.uci.edu/dataset/336/chronic+kidney+disease) and copy the abbrevation to name mapping. Then, go to 383GPT and instruct the LLM to provide you with a pandas script to apply this renaming to all the columns of your dataset. Paste that code below and make any adjustments necessary to run it in your notebook.

In [32]:
rename_mapping = {
'age': 'Age',
'bp': 'Blood Pressure',
'bgr': 'Blood Glucose Random ',
'bu': 'Blood Urea',
'sc': 'Serum Creatinine',
'sod': 'Sodium',
'pot': 'Potassium',
'hemo': 'Hemoglobin',
'pcv': 'Packed Cell Volume',
'wbcc': 'White Blood Cell Count',
'rbcc': 'Red Blood Cell Count',
'al': 'Albumin',
'su': 'Sugar',
'rbc_abnormal': 'Red Blood Cell Abnormal',
'rbc_normal': 'Red Blood Cell Normal ',
'pc_abnormal': 'Pus Cells Abnormal',
'pc_normal': 'Pus Cells Normal',
'pcc_notpresent': 'Pus Cell Clump Not Present',
'pcc_present': 'Pus Cell Clump Present',
'ba_notpresent': 'Bacteria Not Present',
'ba_present': 'Bacteria Present',
'htn_no': 'Hypertension No',
'htn_yes': 'Hypertension Yes',
'dm_no': 'Diabetes Mellitus No',
'dm_yes': 'Diabetes Mellitus Yes',
'cad_no': 'Coronary Artery Disease No',
'cad_yes': 'Coronary Artery Disease Yes',
'appet_good': 'Appetite Good',
'appet_poor': 'Appetite Poor',
'pe_no': 'Pedal Edema No',
'pe_yes': 'Pedal Edema Yes',
'ane_no': 'Anemia No',
'ane_yes': 'Anemia Yes',
'Target_ckd': 'Chronic Kidney Disease',
'Target_notckd': 'Not Chronic Kidney Disease'
}
# Rename the columns using the mapping
cleaned_data.rename(columns=rename_mapping, inplace=True)
# Print the DataFrame to confirm changes
cleaned_data

,Age,Blood Pressure,Blood Glucose Random,Blood Urea,Serum Creatinine,Sodium,Potassium,Hemoglobin,Packed Cell Volume,White Blood Cell Count,...,Coronary Artery Disease No,Coronary Artery Disease Yes,Appetite Good,Appetite Poor,Pedal Edema No,Pedal Edema Yes,Anemia No,Anemia Yes,Chronic Kidney Disease,Not Chronic Kidney Disease
2,0.743243,0.50,0.442060,0.901961,0.432099,0.500000,0.793103,0.000000,0.032258,0.395161,...,False,True,False,True,False,True,False,True,True,False
5,0.770270,1.00,0.901288,0.163399,0.345679,0.766667,0.206897,0.524752,0.548387,0.443548,...,False,True,True,False,True,False,True,False,True,False
7,0.905405,0.50,0.785408,0.862745,0.518519,0.600000,1.000000,0.277228,0.322581,0.233871,...,False,True,True,False,True,False,True,False,True,False
8,0.202703,0.75,0.158798,0.196078,0.160494,0.166667,0.206897,0.059406,0.000000,0.653226,...,True,False,True,False,True,False,False,True,True,False
9,0.783784,1.00,0.399142,0.287582,0.839506,0.666667,0.586207,0.019802,0.096774,0.258065,...,True,False,True,False,False,True,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,0.189189,0.25,0.227468,0.222222,0.074074,0.500000,0.310345,0.683168,0.677419,0.096774,...,True,False,True,False,True,False,True,False,False,True
149,0.216216,0.00,0.115880,0.052288,0.098765,0.600000,0.482759,0.574257,0.612903,0.290323,...,True,False,True,False,True,False,True,False,False,True
150,0.513514,0.00,0.107296,0.235294,0.012346,0.600000,0.448276,0.722772,0.870968,0.274194,...,True,False,True,False,True,False,True,False,False,True
151,0.702703,0.50,0.128755,0.261438,0.098765,0.666667,0.206897,0.623762,0.870968,0.193548,...,True,False,True,False,True,False,True,False,False,True
152,0.689189,0.00,0.150215,0.254902,0.098765,1.000000,0.620690,0.792079,0.677419,0.491935,...,True,False,True,False,True,False,True,False,False,True

## Part 4.3 Augmenting our skills with prompting

In addition, we can also use 383GPT to convert our data manipulation operations between different data manipulation languages and libraries. For example let's prompt 383GPT to convert the following SQL query to a pandas query.

**SQL Query**
```sql
SELECT Target, COUNT(*) AS count
FROM your_table_name
GROUP BY Target;
```

Prompt 383GPT to convert this to a pandas query. Run this query below, then describe what it does. (If you're not familiar with SQL that is okay you need to only comment on the final resulting output.)

In [33]:
target_count = cleaned_data.groupby('Chronic Kidney Disease').size().reset_index(name='count')
# Display the resulting DataFrame
target_count

   Chronic Kidney Disease  count
0                   False    111
1                    True     22

*Describe what the above code does here*

It groups all the records based on the column of Chronic Kidnry disease. Then it takes a count of the all the cases of tru or false and displays it as in the count column.